package enumeration;

public enum ErrorCode
{
  EXPIRED_TOKEN,  ENTITY_NOT_FOUND,  ENTITY_ALREADY_EXISTS,  MISSING_PARAMETER,  AUTH_FAILED,  RESOURCE_NOT_AVAILABLE,  UNSUPPORTED_FORMAT,  FILE_TOO_BIG,  UPLOAD_ERROR;
}
